// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lockstep.Data {
    using System;
    
    
    public enum AbilityCode {
        
        None = 0,
        
        Build = 64542286,
        
        EnergyStore = -161688807,
        
        Health = -2137395588,
        
        Move = 2404337,
        
        Scan = 2570909,
        
        Shield = -1819473015,
        
        Stop = 2587682,
        
        Turn = 2618525,
        
        SetHeight = -2030630903,
    }
}
